### ISSUE TITLE
[Bug]: upgrading from 0.14.1 onwards via APT, removes client from network?

### ISSUE THREAD

**Issue by si458** [gravitl/netmaker#1183]
### What happened?

doing an `apt upgrade` from 0.14.1 to 0.14.2 decided to physically removed the node from the network and never rejoins?
lost physical access to 2 remote computers, going to have to do a site visit now, groan...

### Version

v0.14.2

### What OS are you using?

Linux

### Relevant log output

```shell
NODE1:
Preparing to unpack .../netclient_0.14.2-1_amd64.deb ...
[netclient] 2022-06-04 10:06:22 uninstalling netclient... 
[netclient] 2022-06-04 10:06:24 deleted node martinsserver  on network  myNetwork 

NODE2:
Preparing to unpack .../14-netclient_0.14.2-1_amd64.deb ...
[netclient] 2022-06-04 10:07:40 uninstalling netclient... 
[netclient] 2022-06-04 10:07:43 deleted node maycocksserver  on network  myNetwork
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
This is a known issue with the package manager currently. It will uninstall the client before reinstalling with the new client. We will have this changed in the next release, so it will not uninstall before reinstalling.

In the meantime, rather than use the package manager, you can download and replace the binary directly, using the binaries from the release page.

**Comment by si458** [comment]
@afeiszli this issue still exists with 0.14.3,
the should be a WARNING in the know issues section about this bug,
it happened again to myself, update via apt and need to join the network with a new access key
(i had a backup method of accessing the server this time)

**Comment by afeiszli** [comment]
@mattkasun

**Comment by boospy** [comment]
> @afeiszli this issue still exists with 0.14.3, the should be a WARNING in the know issues section about this bug, it happened again to myself, update via apt and need to join the network with a new access key (i had a backup method of accessing the server this time)

Strange. I had this from 0.14.1 to 0.14.2. But today i've upgraded Server and after the all my clients to 0.14.3. No issue. All clients are Ubuntu 22.04. Server too.

**Comment by afeiszli** [comment]
This has been fixed with the new installer, however, the first upgrade will still cause this issue because it has the old installer. Once you've upgraded once (or install new) you will no longer encounter this issue. Closing this issue

**Comment by si458** [comment]
@afeiszli what new installer? why was this issue closed? this issue still exists with the 0.14.3 versions via APT ?

**Comment by afeiszli** [comment]
If you upgraded from an older version to 0.14.3, you will still experience this issue, because you currently have the old uninstall function in your client. However, on your next upgrade, you will not experience this issue.

**Comment by afeiszli** [comment]
yes, unfortunately we can't change how the existing clients will behave when they upgrade
