### ISSUE TITLE
[Bug]: All Devices - pages issue

### ISSUE THREAD

**Issue by josifpeev** [gravitl/netmaker#3501]
### What happened?

Hello, from version v0.30.0 to the current v0.99.0, there is an issue with the pages in "All Devices" — I can't change the number of items per page from 15 to anything else. For example, I want to see 100 devices per page.

### Version

v0.99.0

### What OS are you using?

Linux

### Relevant log output

```shell

```

### Contributing guidelines

- [x] Yes, I did.

**Comment by Aceix** [comment]
hi @josifpeev let me look into this

**Comment by imadtassaoui** [comment]
Hi @josifpeev, the issue has been fixed in v0.99.0. Thanks for the heads-up!

**Comment by josifpeev** [comment]
Hello, 
I'm with version 0.99.0 and is not fixed.
All Devices - not fixed
Nodes - is working on all previous version

**Comment by abhishek9686** [comment]
> Hello, I'm with version 0.99.0 and is not fixed. All Devices - not fixed Nodes - is working on all previous version

@josifpeev, you need to pull the latest image of v0.99.0
Run `docker compose pull && docker compose up -d`

**Comment by josifpeev** [comment]
Hello,
I pulled it, but still is not working **on All Devices section**

**Comment by imadtassaoui** [comment]
> Hello, I pulled it, but still is not working **on All Devices section**

Let me check, 1 second

**Comment by imadtassaoui** [comment]
> Hello, I pulled it, but still is not working **on All Devices section**

I can confirm the issue is fixed now. Make sure to re-pull.

**Comment by josifpeev** [comment]
re-pull is done but,
I can confirm - **is not fixed yet**

**Comment by Aceix** [comment]
Hello @josifpeev 
we made a patch. pls check again; re-pull and hard-refresh

**Comment by josifpeev** [comment]
It's working now! 
Thank you, and have a nice holiday
